### ISSUE TITLE
Records with typed keys failing conversion

### ISSUE THREAD

**Issue by Josh68** [fabien0102/ts-to-zod#128]
## Feature description

I'm not sure whether this is an issue in Zod itself or something not implemented in this library, but I'm testing conversion of some existing type definitions to Zod, and the conversion is failing on `Record`s with `enum`s or union types as keys.

A relevant issue from Zod: https://github.com/colinhacks/zod/issues/55

### Input

```ts
// typescript type or interface causing the output

enum SomeEnum = {
  Foo: "Foo",
  Bar: "Bar"
};

interface MyInterface {
  someField: Record<SomeEnum, string>
}
```

I get the same (or similar) failure if I convert the enum to a union:

```ts
  type SomeUnion = "Foo" | "Bar"
```

### Output

```ts
// Expected Zod schemas
// These are valid, AFAICT

const myInterfaceSchema = z.object({
  someField: z.record(z.nativeEnum(SomeEnum), z.string())
});

or

const myInterfaceSchema = z.object({
  someField: z.record(z.union([z.literal("Foo"), z.literal("Bar")]), z.string())
});
```

Thanks for any ideas, thoughts

**Comment by kapitanluffy** [comment]
Bumping for visibility 👍

**Comment by juliomuhlbauer** [comment]
Same issue with supabase-to-zod
