### ISSUE TITLE
Schema for picked and nullabled type is not nullable

### ISSUE THREAD

**Issue by t-animal** [fabien0102/ts-to-zod#129]
## Bug description

When picking a subtype and marking it nullable, the generated zod schema loses the nullable attribute

### Input

```ts
export type foo = {
        bar: number;
}

export type bla = foo['bar'] | null
```

### Expected output

```ts
export const blaSchema = fooSchema.shape.bar.nullable();
```

### Actual output

```ts
export const blaSchema = fooSchema.shape.bar
```

**Versions**

- Typescript: `4.9.3`
- Zod: `3.21.4`

**Comment by fabien0102** [comment]
Hey, I guess you did a mistake writing the issue since the "Expected output" and "Actual output" are identical.

But running it locally, I can see than the actual output is the following:

```ts
export const fooSchema = z.object({
  bar: z.number(),
});

export const blaSchema = fooSchema.shape.bar;
```

Good catch!

**Comment by t-animal** [comment]
Yes, sorry. I have updated the issue.
