### ISSUE TITLE
Generated type validation doesn't work for non-optional any property

### ISSUE THREAD

**Issue by tvillaren** [fabien0102/ts-to-zod#140]
## Bug description

When using the `any` keyword to accept any input for a property, like this:

```ts
export interface Citizen {
  name: any
};
```

`ts-to-zod` generates the right output 

```ts
export const citizenSchema = z.object({
  name: z.any()
});
```

However, as mentioned in issue https://github.com/colinhacks/zod/issues/1628, the type inference from `zod` makes the `name` property optional, failing the `ts-to-zod` generated type validation (see https://github.com/fabien0102/ts-to-zod/commit/52cf4f7d33e59713a53edebd6bcaf3982b201bd3 for a failing test case). 

Indeed, when looking at the inferred type via `z.infer<typeof citizenSchema>` we get the following: 

```ts
type Citizen = {
  name?: any
}
```
which doesn't match the initial type, thus fail validation. 

There is no full consensus on the fix on the `zod` Github. 
👉 An user proposed a [workaround](https://github.com/colinhacks/zod/issues/1628#issuecomment-1336678982) but that would mean using a custom function instead of `z.object()`. 
👉 We could ignore this specific generated type validation error, but it may come from various sources.
👉 We could live with it, but that would mean only supporting `any` for optional properties (and thus, warn `ts-to-zod` users about this upon generation). 

Happy to try to fix this but not sure toward which direction we could go 🤷

**Comment by fabien0102** [comment]
Interesting! I guess we can relax the validator for this usecase. The validator is here to help discovering missing types, so I think it's fine to ignore this case, I can have a look on Monday if you want! 😊

Have a nice weekend

**Comment by tvillaren** [comment]
Hello @fabien0102, 

Have you had a chance to look at this? 
If not, I can give it a try but I'm not sure what to do to ignore this case. Any pointer would be nice! Thx.

**Comment by fabien0102** [comment]
As you probably guessed, I had no time whatsoever 🙈 Until now! 😁 

This should be fixed, thanks again for the clear reporting and follow up
