### ISSUE TITLE
Add support for more `@format` types (e.g. "date", "ipv4", etc.)

### ISSUE THREAD

**Issue by denk0403** [fabien0102/ts-to-zod#144]
## Feature description

With the introduction of the `datetime()` method in Zod `3.20.0` and the `ip()` method in Zod `3.21.0` for string validation, it would be nice to add JSDoc support for [the corresponding format types](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-defined-formats).

### Input

```ts
export interface Info {
  /** @format date-time */
  dateTime: string;

  /** @format date */
  date: string;

  /** @format ipv4 */
  ipv4: string;

  /** @format ipv6 */
  ipv6: string;

  /**
   * An IPv4 or IPv6 string.
   * @format ipv4
   * @format ipv6
   */
  ip: string;
}
```

### Output

```ts
export const infoSchema = z.object({
  /** @format date-time */
  dateTime: z.string().datetime(),

  /** @format date */
  date: z.string().regex(/^\d{4}-\d\d-\d\d$/);

  /** @format ipv4 */
  ipv4: z.string().ip({version: 4}),

  /** @format ipv6 */
  ipv6: z.string().ip({version: 6}),

  /**
   * An IPv4 or IPv6 string.
   * @format ipv4
   * @format ipv6
   */
  ip: z.string().ip(),
}
```

If there are positive signals for this feature, I am open to working on it.

**Comment by fabien0102** [comment]
I like the idea for built-in zod format, I think the regex for the date is a too much from my point of view. This said, if we can provide a format to regex config somehow, this could be cool!

**Comment by samuliasmala** [comment]
> I like the idea for built-in zod format, I think the regex for the date is a too much from my point of view. This said, if we can provide a format to regex config somehow, this could be cool!

Now the recent Zod 3.23 [supports `date()` validation](https://zod.dev/?id=dates) so would it be now ok to add that? I'm happy to create a PR for it.

**Comment by tvillaren** [comment]
Hello @samuliasmala, 
I think it does make sense to add it yet. 

Feel free to open a PR indeed :)

**Comment by samuliasmala** [comment]
Great! I have the PR ready but before submitting it I wanted to ask what's your opinion about `time()` and `duration()` formats which were also [added in Zod 3.23](https://github.com/colinhacks/zod/releases/tag/v3.23.0) and are mentioned in [OpenAPI Formats Registry](https://spec.openapis.org/registry/format/). I'd be happy to include them as well if you approve.
