### ISSUE TITLE
can not use in es module project

### ISSUE THREAD

**Issue by wangfengyuan** [fabien0102/ts-to-zod#146]
## Bug description

minimal reproduction link https://stackblitz.com/edit/github-8cm7yx?file=package.json

run
```
pnpm run gen:zod
```
the error message like below 

```
 ›   Error: "ts-to-zod.config.js" invalid:
 ›     require() of ES Module /home/projects/github-8cm7yx/ts-to-zod.config.js from 
 ›   /home/projects/github-8cm7yx/node_modules/.pnpm/ts-to-zod@3.1.3/node_modules/ts-to-zod/lib/cli.js not supported.
 ›   ts-to-zod.config.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains 
 ›   "type": "module" which declares all .js files in that package scope as ES modules.
 ›   Instead rename ts-to-zod.config.js to end in .cjs, change the requiring code to use dynamic import() which is 
 ›   available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in 
 ›   /home/projects/github-8cm7yx/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

### Input

```ts
// typescript type or interface causing the output
```

### Expected output

```ts
// Expected Zod schemas
```

### Actual output

```ts
// Actual Zod schemas
```

**Versions**

- Typescript: ^5.0.4
- Zod: latest

**Comment by paxperscientiam** [comment]
I have the same issue with a vitejs project.

 "typescript": "^5.2.2",
"zod": "^3.22.2"
"ts-to-zod": "^3.1.3"

My work around is to temporarily remove "type" from package.json

**Comment by maximeq** [comment]
I ran into a related issue trying to use ts-to-zod in a `"type":"module"` package.
The `ts-to-zod-config.js` config file would not load and the error would just be:
```
 ›   Error: Missing 1 required arg:
 ›   input file (typescript)
 ›   See more help with --help
```

It works if I change the extension to `.cjs`.

I'm not sure if it's a bug or expected, but the error was not very clear and it took me a while to get to this thread.
If users are expected to use `ts-to-zod-config.cjs` in a module package, maybe worth specifying that in the doc ?
