### ISSUE TITLE
ts-to-zod is using Prettier v2 which autoloads configs and causes errors due to unsupported plugins

### ISSUE THREAD

**Issue by martitv** [fabien0102/ts-to-zod#158]
## Bug description

Ref this issue: #https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/214

> Hey! Thanks for that repo. The problem is definitely that `ts-to-zod` is using Prettier 2 to do some formatting internally, we only support Prettier v3, and they're both using your config file (plus Prettier v2 autoloads plugins by default so even without the config it'd still break):
> 
> <img alt="Screenshot 2023-09-19 at 09 14 22" width="302" src="https://user-images.githubusercontent.com/614993/268968453-67926fba-2112-40d7-b1e2-3da8102c16f3.png"> <img alt="Screenshot 2023-09-19 at 09 14 34" width="1158" src="https://user-images.githubusercontent.com/614993/268968434-eb915f1b-ba87-472e-8fa0-a5f290ab0588.png">
> That said, I did figure out a workaround but it requires a super strange setup for the config to stop v2 from loading `prettier-plugin-tailwindcss` while still allowing `ts-to-zod` to use Prettier and your config.
> 
> You'll want to customize your prettier config such that:
> 
> * Prettier v2 autoloading is disabled — otherwise the plugin will always be picked up because of the package name and you'll keep getting the error
> * Configure Prettier to only load the plugin for files matching `app/*`. You do this via the `overrides` key in your config.
> 
> This setup looks like this:
> 
> ```js
> /** @type {import('prettier').Config} */
> module.exports = {
>   // Stop autoloading in Prettier v2
>   // This is a warning in Prettier v3
>   // but you can safely ignore it
>   pluginSearchDirs: [],
> 
>   overrides: [
>     // Only load `prettier-plugin-tailwindcss` when scanning the app dir
>     // This _should_ work so long as `ts-to-zod` doesn't run prettier on any files in `app/*`
>     {
>       files: ["app/*"],
>       options: {
>         plugins: ["prettier-plugin-tailwindcss"],
>       },
>     },
>   ],
> };
> ```
> 
> So, unfortunately nothing _we_ can do to fix this on our end but the above Prettier config might fix things for you. Hope that helps! ✨

**Versions**

- Typescript: `v5.1.6`
- Zod: `v3.1.3`

**Comment by martitv** [comment]
Bump!
Prettier-plugin-tailwindcss is a super important plugin for using tailwind! Please fix this so it is possible to use both of these libraries at the same time!

**Comment by schiller-manuel** [comment]
#169 fixes this
