### ISSUE TITLE
3.3.0 is not on npm

### ISSUE THREAD

**Issue by Diokuz** [fabien0102/ts-to-zod#175]
Looks like npm publish action failed https://github.com/fabien0102/ts-to-zod/actions/runs/6800940931/job/18490652586 and there still 3.2.0 is the latest version https://www.npmjs.com/package/ts-to-zod

Also, what do you think about moving `typescript` dependency from `dependencies` to `peerDependencies`? Or maybe replacing `^4.0.0` with `*`. I cant upgrade typescript in my repo (without of duplication in node_modules) just because of ts-to-zod package)

**Comment by tvillaren** [comment]
Hello, 

#176 will fix NPM publication.

**Comment by tvillaren** [comment]
With regards to listing `typescript`, I would advocate for using `peerDependencies` to help avoiding version conflicts and  keep your package lightweight.

**Comment by schiller-manuel** [comment]
seems like I cannot re-run the build job to publish 3.3.0, however now we have 3.4.0 on npmjs.com:
https://www.npmjs.com/package/ts-to-zod/v/3.4.0

🎉 

about typescript: we cannot use `peerDependencies` since ts-to-zod directly uses the typescript API
