### ISSUE TITLE
It seems that optional parameters are not supported

### ISSUE THREAD

**Issue by surgit** [fabien0102/ts-to-zod#179]
## Bug description

It seems that optional parameters are not supported

### Input

```ts
export type CONCAT = (...args: string[]) => string
```

### Expected output

```ts
import { z } from "zod";

export const concatSchema = z
  .function()
  .args(z.rest(z.string())) // Not sure here
  .returns(z.string());
```

### Actual output

```ts
✖ Validating generated types
 ›   Error: 'concatSchema' is not compatible with 'CONCAT':
 ›   Argument of type '(args_0: string[], ...args_1: unknown[]) => string' is not assignable to parameter of type 'CONCAT'.
 ›     Types of parameters 'args_0' and 'args' are incompatible.
 ›       Type 'string' is not assignable to type 'string[]'.
 ›   'CONCAT' is not compatible with 'concatSchema':
 ›   Argument of type 'CONCAT' is not assignable to parameter of type '(args_0: string[], ...args_1: unknown[]) => string'.
 ›     Types of parameters 'args' and 'args_0' are incompatible.
 ›       Type 'string[]' is not assignable to type 'string'.
```

**Versions**

- Typescript: `v4.8.4`
- Zod: `3.22.4`

**Comment by tvillaren** [comment]
Hello, 

The actual solution in `zod` itself doesn't seem to exist for this validation: see https://github.com/colinhacks/zod/issues/1282 &  https://github.com/colinhacks/zod/issues/2859 if I read correctly. 

So not sure what would be the actual implementation for `ts-to-zod`. 
@surgit: were you able to write "by hand" a working validator for your use case (without the `unknown` issue mentioned on the tickets I linked)?

**Comment by schiller-manuel** [comment]
closing since no feedback was given
