### ISSUE TITLE
Optional arrays are not marked optional in Zod schema

### ISSUE THREAD

**Issue by LaCuneta** [fabien0102/ts-to-zod#18]
## Bug description

If I have a type with an optional array of items, the result in the Zod schema is not marked `optional()`.  A validation error is generated:

```
✖ Validating generated types
 ›   Error: 'A' is not compatible with 'aSchema':
 ›   Argument of type 'A' is not assignable to parameter of type '{ values: string[]; }'.
 ›     Types of property 'values' are incompatible.
 ›       Type 'string[] | undefined' is not assignable to type 'string[]'.
 ›         Type 'undefined' is not assignable to type 'string[]'.
error Command failed with exit code 2.
```

### Input

```ts
// typescript type or interface causing the output
export type A = {
  values?: Array<string>
}
```

### Expected output

```ts
// Generated by ts-to-zod
import { z } from "zod";

export const aSchema = z.object({
  values: z.array(z.string()).optional(),
});
```

### Actual output

```ts
// Actual Zod schemas
// Generated by ts-to-zod
import { z } from "zod";

export const aSchema = z.object({
  values: z.array(z.string()),
});
```

**Versions**

- ts-to-zod: `v1.0.1`
- Typescript: `v4.2.3`
- Zod: `v3.0.0-alpha.39`

**Comment by fabien0102** [comment]
Good catch! Thanks for the report!

**Comment by eugenebalts** [comment]
this problem isn't solved.
"typescript": "^5.5.4"
"zod": "^3.23.8"

![image](https://github.com/user-attachments/assets/88d72c2a-4213-4199-96da-95cfb7b001fc)

**Comment by tvillaren** [comment]
I'm not sure what we're seeing on your screenshot @eugenebalts: the schema does have the `.optional()` modifier.

**Comment by tvillaren** [comment]
Closing, as `ts-to-zod` handles optional arrays. 
Feel free to open another ticket if you run into a different issue (or comment here with more details).
