### ISSUE TITLE
[Project] Issue while adding more tests for validateGeneratedType

### ISSUE THREAD

**Issue by tvillaren** [fabien0102/ts-to-zod#186]
Hey @fabien0102,

I'm creating an issue for something which doesn't seem like a bug, at least wasn't able to reproduce in a "real-life" project but some of the tests I'm adding (for https://github.com/fabien0102/ts-to-zod/pull/135) now fail after a rebase on `main` (post-release of 3.4.1).

## Context 

A couple of month ago, I raised https://github.com/fabien0102/ts-to-zod/issues/140 because some validations were failing on my project due to a bug in `zod`. 

I had similar validation fail after working on a built version of branch introducing _import handling_ so decided to add some tests (https://github.com/fabien0102/ts-to-zod/pull/135/commits/74b10b32e3c9bc6d6e05843a408e3a14ecdd5788) to cover specific identifier references triggering optional any. 
👉 Those tests don't pass anymore since I rebased the branch 
👉 They still pass on another branch (https://github.com/tvillaren/ts-to-zod/tree/feat-handle-zod-imports) which I haven't rebased

I created a simple branch from the current `main#HEAD` with a simple not passing test (simple union in an object): https://github.com/tvillaren/ts-to-zod/actions/runs/7062596244/job/19226755896

I'm a bit lost, tried different things including fiddling with the [fixOptionalAny](https://github.com/fabien0102/ts-to-zod/blob/main/src/utils/fixOptionalAny.ts) file to add more edge cases but outputting the actual types from the `vfs` (https://github.com/fabien0102/ts-to-zod/commit/acda15118947a8662b6289c20dfd241236681b28) gives me some discrepancies in type inference. 

I'm starting to thing the Typescript inference doesn't work the same way in VFS that on my system (I checked version of TS passed and they are the same). 
If you have any idea (or @schiller-manuel as you seem to have updated this project quite a lot recently 😉), I'm all hear!

(I'm running those on a Mac)

Thanks!

**Comment by schiller-manuel** [comment]
Hi @tvillaren,

I had a quick look at the simplified example and I saw that the schema is incorrect.
The parameter of `z.union()` should be an array: 

```diff

diff --git a/src/core/validateGeneratedTypes.test.ts b/src/core/validateGeneratedTypes.test.ts
index 78fe5ea..bceb9c2 100644
--- a/src/core/validateGeneratedTypes.test.ts
+++ b/src/core/validateGeneratedTypes.test.ts
@@ -221,7 +221,7 @@ describe("validateGeneratedTypes", () => {
       import { z } from "zod";
   
       export const citizenSchema = z.object({
-          heroAliases: z.union(z.string(), z.number())
+          heroAliases: z.union([z.string(), z.number()])
       });
       `,
       relativePath: "source.zod.ts",
```

I did not check the other code, so it can be that the reproducer example was not representative for the real issue you are experiencing.
Can you check again?

**Comment by fabien0102-crabnebula** [comment]
Yeah, `expectType` is not the most robust things, it's actually a known issue, the main idea of this `validateGeneratedType` is just to help me to catch the non-handled cases 😉 I think I saw better support for type assertion somewhere but never had the time to try

**Comment by tvillaren** [comment]
Yes, I was looking at alternatives. Found the[ type-testing](https://github.com/MichiganTypeScript/type-testing/tree/faf260edef7e619e7b9a4eb3666e43d2660893fe) library on [Advent of Typescript](https://typehero.dev/aot-2023)

**Comment by tvillaren** [comment]
Closing, implemented some more cases to [fixOptionalAny](https://github.com/fabien0102/ts-to-zod/blob/main/src/utils/fixOptionalAny.ts)
