### ISSUE TITLE
Schema with default: null becomes default("null") in generated Zod code

### ISSUE THREAD

**Issue by robogeek** [fabien0102/ts-to-zod#188]
## Bug description

An OpenAPI schema with `default: null` becomes `default("null")` in generated Zod code

For full information see: https://github.com/fabien0102/openapi-codegen/issues/212

### Input

```ts
  /**
   * Long name of program for human readability.
   *
   * @example Residential Time of Use-A
   * @default null
   */
  programLongName?: string | null;
  /**
   * Short name of energy retailer providing the program.
   *
   * @example ACME
   * @default null
   */
  retailerName?: string | null;
```

### Expected output

```ts
programLongName: z.string().optional().nullable().default(null),
  retailerName: z.string().optional().nullable().default(null),
```

### Actual output

```ts
programLongName: z.string().optional().nullable().default("null"),
  retailerName: z.string().optional().nullable().default("null"),
```

**Versions**

- Typescript: `v4.5.3`
- Zod: `v3.22.4`

**Comment by schiller-manuel** [comment]
`null` is currently not handled in the @default JSDoc parsing, see https://github.com/fabien0102/ts-to-zod/blob/main/src/core/jsDocTags.ts#L177

**Comment by tvillaren** [comment]
It would make sense to handle it, wouldn't it?

**Comment by schiller-manuel** [comment]
> It would make sense to handle it, wouldn't it?

sure!
Ideally we would also validate the @default value, i.e. only accept `null` if the type is actually nullable.

**Comment by tvillaren** [comment]
Or set it to `nullable` if it detects `null` as a default. 

This would be consistent with the already implemented behaviour of removing the question mark when a property has a default: https://github.com/fabien0102/ts-to-zod/blob/7c0835bdae9db02da4951ca13cd3d0a7a6c2891f/src/utils/resolveDefaultProperties.ts#L18-L42
