### ISSUE TITLE
The help does not show on command line

### ISSUE THREAD

**Issue by FlorianCousin** [fabien0102/ts-to-zod#196]
## Bug description

The help of ts-to-zod is not accessible.

### Input

On Windows 10, I use Cmder and run the following commands :
```
npm install ts-to-zod --save-dev
npx ts-to-zod --help
```

### Expected output

The help of the command line.

### Actual output

```
 »   Error: Parsing --help
 »      Command tstozod not found.
 »   See more help with --help
```

**Versions**

- Typescript: `v5.3.3`
- Zod: `v3.22.4`
- ts-to-zod: `v3.6.0`

**Comment by FlorianCousin** [comment]
The command `npx ts-to-zod` exists because whe I run `npx ts-to-zod`, I get the folowwing :
```
 »   Error: Missing 1 required arg:
 »   input file (typescript)
 »   See more help with --help
```

**Comment by tvillaren** [comment]
Hello @FlorianCousin, 

I found a fix for this but cannot test it on Windows (see https://github.com/fabien0102/ts-to-zod/pull/222)
Would you mind testing on your side (if this issue is still relevant to you)? 🙏

**Comment by FlorianCousin** [comment]
- I cloned the GitHub repository
- I ran `npm install`
- I ran `npm run build`
- I ran `npx ts-to-zod --help`

It seems to work because I got the following.
```sh
λ npx ts-to-zod --help
Generate Zod schemas from a Typescript file

USAGE
  $ ts-to-zod  --all
  $ ts-to-zod  --config example
  $ ts-to-zod  --config example/person
  $ ts-to-zod  --config config

ARGUMENTS
  INPUT   input file (typescript)
  OUTPUT  output file (zod schemas)

FLAGS
  -a, --all                    Execute all configs
  -c, --config=<option>        Execute one config
                               <options: example|example/person|config>
  -h, --help                   Show CLI help.
  -i, --init                   Create a ts-to-zod.config.js file
  -k, --keepComments           Keep parameters comments
  -v, --version                Show CLI version.
  -w, --watch                  Watch input file(s) for changes and re-run related task
      --inferredTypes=<value>  Path of z.infer<> types file
      --skipParseJSDoc         Skip the creation of zod validators from JSDoc annotations
      --skipValidation         Skip the validation step (not recommended)

DESCRIPTION
  Generate Zod schemas from a Typescript file

EXAMPLES
  $ ts-to-zod src/types.ts src/types.zod.ts
```

Though, I could not test with `ts-to-zod` as a dependency of another project because #222 is not released, but I guess it works the same.
