### ISSUE TITLE
z.coerce in ts-to-zod

### ISSUE THREAD

**Issue by fucksophie** [fabien0102/ts-to-zod#201]
## Feature description
A comment such as 
```
/*
* @coerce true
*/
hello: number;
```
will turn the resulting `z.number()` into `z.coerce.number()`
### Input

```ts
/*
* @coerce true
*/
hello: number;
```

### Output

```ts
hello: z.coerce.number()
```

**Comment by schiller-manuel** [comment]
Feel free to create a PR!

**Comment by fucksophie** [comment]
Just saw, this feature has been implemented in #125, just that the PR's author hasn't written any tests for it yet..

**Comment by schiller-manuel** [comment]
https://github.com/fabien0102/ts-to-zod/releases/tag/v3.13.0 allows to append to a schema, does this solve your issue?

**Comment by fucksophie** [comment]
Yup, does.
