### ISSUE TITLE
Generate schema from types within one file

### ISSUE THREAD

**Issue by kirillkurko** [fabien0102/ts-to-zod#219]
## Bug description

In versions `3.6.1` and below (tested down to `3.1.2`), it was possible to generate zod schemas from types within a single file using a command similar to the one below:

```shell
# Note that the input file matches the output file
npx ts-to-zod some-file.ts some-file.ts
```

After updating to version `3.7.3` (`3.7.0`, `3.7.1` and `3.7.2` have not been tested), the above command results in an error and no zod schemas are generated. The same problem occurs when using version `3.8.0`.

### Input

1. Create some file with types, e.g. `some-file.ts`.
2. Try generating zod schemas from types in `some-file.ts` and output the generated schemas to the same `some-file.ts`.

### Expected output

Zod schemas are generated.

### Actual output

No zod schemas are generated.

**Versions**

- Typescript: `v5.2.2`
- Zod: `v3.22.4`

**Comment by kirillkurko** [comment]
Hey @tvillaren I can confirm that it works when generating to another file. And zod schemas are generated when running with `--skipValidation` flag on, so yes, this has something to do with validation

**Comment by kirillkurko** [comment]
Hey @tvillaren, I can confirm that it works when generating to another file. And zod schemas are generated when running with the `--skipValidation` flag on, so yes, this has something to do with validating the files

**Comment by tvillaren** [comment]
Thanks for reporting, I found the issue. 
I need to add test cases to cover this and prevent regression, before merging. 

I commited the fix ([20175f4](https://github.com/fabien0102/ts-to-zod/commit/20175f458f14a9a6b31a523f838bd297f0627de0)) if you need to use it or would like to try it and confirm it does fix your issue 🙏

**Comment by kirillkurko** [comment]
Sounds great, thank you for such a quick response and finding a solution! I'll validate the fix tomorrow and let you know if it works

**Comment by kirillkurko** [comment]
Hi @tvillaren, sorry for the late reply, but I just checked the fix and it solved the problem, thanks! 🚀
