### ISSUE TITLE
Error: Module '"zod"' has no exported member 'z'.

### ISSUE THREAD

**Issue by Southclaws** [fabien0102/ts-to-zod#22]
## Bug description

Can't run the command. I tried with npx and also installing as a dev dependency but even running on a super simple type results in an import error.

### Input

```ts
export interface SomeType {
  a: string
}
```

### Actual output

```ts
❯ yarn ts-to-zod ./src/temp.ts ./src/out.ts
yarn run v1.22.10
✖ Validating generated types
 ›   Error: Module '"zod"' has no exported member 'z'.
error Command failed with exit code 2.
```

**Versions**

- Typescript: `4.2.2`
- Zod: `1.11.13`

**Comment by fabien0102** [comment]
Hello @Southclaws,
This is totally normal, this library is only compatible with the latest version of zod (v3)

![image](https://user-images.githubusercontent.com/1761469/119253331-0c021280-bbb1-11eb-8c41-61c720364b9e.png)

(Sorry for the late answer, I totally missed this notification 🙄)

**Comment by Southclaws** [comment]
Oh, yeah apparently we were on v1 somehow and I had no idea!

**Comment by fabien0102** [comment]
No problem, happens to everybody 😅
