### ISSUE TITLE
Error: Debug Failure. False expression: Negative numbers should be created in combination with createPrefixUnaryExpression

### ISSUE THREAD

**Issue by hlg-facai** [fabien0102/ts-to-zod#227]
## Bug description

![截屏2024-04-12 10 35 35](https://github.com/fabien0102/ts-to-zod/assets/38316077/1ac1fbfe-1cca-46d5-bb64-b28f48199409)

### Input

```ts
export interface Test {
     /**
     * @default -45
     */
     angle: number;
}
```

### Actual output
Error: Debug Failure. False expression: Negative numbers should be created in combination with createPrefixUnaryExpression

**Versions**

- Typescript: `v5.4.5`
- Zod: `v3.22.4`

**Comment by tvillaren** [comment]
Hello, 

I was able to generate the following: 
```ts
// Generated by ts-to-zod
import { z } from "zod";

export const testSchema = z.object({
  angle: z.number().default(-45),
});
```
on last version of `ts-to-zod` (3.8.2)
