### ISSUE TITLE
import modlue from  node_modules  will error

### ISSUE THREAD

**Issue by hukangbao** [fabien0102/ts-to-zod#235]
### Input
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";

export interface IPublicReviewConfigServiceClient {
 
    getPublicReviewConfig(input: GetPublicReviewConfigRequest, options?: RpcOptions): UnaryCall<GetPublicReviewConfigRequest, GetPublicReviewConfigResponse>;
    
    updatePublicReviewConfig(input: UpdatePublicReviewConfigRequest, options?: RpcOptions): UnaryCall<UpdatePublicReviewConfigRequest, UpdatePublicReviewConfigResponse>;
}

```ts
// typescript type or interface causing the output
```

### Expected output
Validating generated types
 ›   Error: 'iPublicReviewConfigServiceClientSchema' is not compatible with 
 ›   'IPublicReviewConfigServiceClient':
 ›   Argument of type '{}' is not assignable to parameter of type 
 ›   'IPublicReviewConfigServiceClient'.
 ›     Type '{}' is missing the following properties from type 
 ›   'IPublicReviewConfigServiceClient': getPublicReviewConfig, 
 ›   updatePublicReviewConfig

```ts
// Expected Zod schemas
```

### Actual output

```ts
// Actual Zod schemas
```

**Versions**

- Typescript: `v0.0.0`
- Zod: `v0.0.0`

**Comment by tvillaren** [comment]
Hello, 
This is not due to imports but to the fact you use an unsupported method signature, same as #234 that you reported earlier (and #220).
