### ISSUE TITLE
Declaring type from property of other type after importing the other type fails

### ISSUE THREAD

**Issue by t-animal** [fabien0102/ts-to-zod#244]
## Bug description

Types can either be built up from many individual sub-types (`type A = ...; type B = ...; type c = {a: A, B: b}`) or by pointing into a larger type (`type C = {a: {...}, b: {...}}; type A = C['a']; type B = C['b']`). The latter is especially useful, when referencing an imported type, e.g. importing a `DatabaseItem` type in a API declaration and then returning only a part of it (e.g. `type AddressApiReturnValue = DatabaseItem['address']`), because otherwise the `DatabaseItem` would have to be constructed from all potential API sub-types.

In zod this would be done by accessing the shape property and getting the respective item (e.g. `databaseItemSchema.shape.address`), however ts-to-zod returns a warning:

*Warning: Some schemas can't be generated due to direct or indirect missing dependencies: addressApiReturnValueSchema*

and does not generate the type. Using that type then causes validation errors in turn.

Edit: **This example works just fine,** only when the type is exported and imported, things break. See see conversation below:

### Input

```ts
export type meh = {foo: {bar: number}}

export type meh2= foo['bar']
```

### Expected output

```ts
// Generated by ts-to-zod
import { z } from "zod";

export const mehSchema = z.object({
    foo: z.object({
        bar: z.number(),
    }),
});

export const meh2Schema = mehSchema.shape.bar
```

### Actual output

```ts
// Generated by ts-to-zod
import { z } from "zod";

export const mehSchema = z.object({
    foo: z.object({
        bar: z.number(),
    }),
});
```

**Versions**

- Typescript: "typescript": "^5.2.2"
- Zod: `"zod": "^3.23.8"
- "ts-to-zod": "^3.8.5",

**Comment by tvillaren** [comment]
Hello @t-animal ,

Don't you mean to write: 
```ts
export type meh = { foo: { bar: number } };

export type meh2 = meh["foo"]["bar"];
```

In that case, generating without validation (using the `--skipValidation` flag) generates:
```ts
// Generated by ts-to-zod
import { z } from "zod";

const mehSchema = z.object({
  foo: z.object({
    bar: z.number(),
  }),
});

const meh2Schema = mehSchema.shape.foo.shape.bar;
```

and `z.infer<typeof meh2Schema>` seems to be inferred as a number in my IDE. 

There might be a bug with the validation of generated types but you can still generate with the flag.

**Comment by tvillaren** [comment]
Nevermind, validation seems to work with the fixed input. 
So you should be able to generate what you need.

**Comment by t-animal** [comment]
Oh, yes. How embarrassing... I expected the error in zod so I didn't double-check my boiled-down example. In fact, its a bit more complicated than I thought at first, and I'm not quite sure any more whether this qualifies as a bug. It has to do with the type being exported and imported like this:

```
//test.ts
export type meh = { foo: { bar: number } };

export type meh2 = meh["foo"]["bar"]; // this actually works just fine

//test2.ts
import { meh } from "./test";

export type meh2 = meh["foo"];
```

Now, when I convert test2: `npx ts-to-zod test.ts test2.ts` it brings up the aforementioned warning:
```
 ›   Warning: Some schemas can't be generated due to direct or indirect missing dependencies:
 ›   meh2Schema
```

I _guess_ it has to do with the approach of only one converting one file at a time, thus ts-to-zod has no idea that `meh` was already converted in the other file. So... I guess this is not really a bug, but a limitation? Anyways, it's a pretty big drawback in my opinion (see my example above with the DB/API example).

I'm not sure how to approach this, so feel free to close the issue if you don't want to fix it.

**Comment by tvillaren** [comment]
Yes, in that case, I can see a bug. 

To handle Zod Schema in multiple file, you need to add them to the `ts-to-zod.config.js` and generate _in the right order_   

```js
/**
 * ts-to-zod configuration.
 *
 * @type {import("./src/config").TsToZodConfig}
 */
module.exports = [
  { name: "a", input: "example/a.ts", output: "example/a.zod.ts" },
  { name: "b", input: "example/b.ts", output: "example/b.zod.ts" },
];
```

This handles automatically imported / exported Zod Schemas and works quite well but there are still some edge cases 😉 

In your case, expected output should be: 

```ts
// Generated by ts-to-zod
import { z } from "zod";

import { mehSchema } from "./test.zod";

export const meh2Schema = mehSchema.shape.foo;
```

I will have a look

**Comment by tvillaren** [comment]
This was an easy fix eventually. 
It will work only if you declare your types in the config file (as described in [this comment](https://github.com/fabien0102/ts-to-zod/issues/244#issuecomment-2186647670))
