### ISSUE TITLE
Import types with a type notation to avoid Typescript errors when verbatimModuleSyntax enabled

### ISSUE THREAD

**Issue by sleewoo** [fabien0102/ts-to-zod#263]
## Bug description

Types imported without `type` notation.
When `verbatimModuleSyntax` enabled in `tsconfig.json`, `tsc` throws error `TS1484`:

```
'SnippetLogicRule' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled
```

### Input

```ts
export type SnippetLogicRule = {
  or?: Array<SnippetLogicRule>;
  val?: string;
  var?: string;
  logic: "eq" | "ne" | "in" | "ni" | "is_null" | "is_not_null";
};
```

### Expected output

```ts
import type { SnippetLogicRule } from "/tmp/1edfb19beb32d8901bd9077e1c4f4711.ts"
```

### Actual output

```ts
import { SnippetLogicRule } from "/tmp/1edfb19beb32d8901bd9077e1c4f4711.ts"
```

https://transform.tools/typescript-to-zod repro:

![Screenshot_20240822_213023](https://github.com/user-attachments/assets/6a6460ff-cedf-4eaf-b485-1d4e1af9a25f)

**Versions**

- Typescript: `v5.5.4`
- Zod: `v3.11.0`

Actually using `generate` / `getZodSchemasFile` api.
Can we somehow tell api the output is typescript and it is safe to insert `type` notation.
Perhaps adding new option to `GenerateProps`?

For now have to use `AST` on generated code to insert `type` notation, which is a pretty awkward overkill.

Thank you for great lib!

**Comment by tvillaren** [comment]
Hello @sleewoo, 

Thanks for reporting. 

The `generate` method only produces Typescript files: the CLI version of the library goes through the generation step first, and relies on `ts.transpileModule` when JS is expected after. 
So the output will always be Typescript. 

As several import use cases have been added over time (3rd party, zod imports...), we would need to handle all of those (e.g. keeping `type` annotation for 3rd party imports, adding it when needed for Zod ones). 

If you want to invest some time into digging into this, and propose a PR, that would be appreciated!

**Comment by sleewoo** [comment]
Hello @tvillaren 
pushed a try to solve this (minor) issue,
had you a chance to take a look?

Thanks.

**Comment by sleewoo** [comment]
@tvillaren format fixed, good to recheck

**Comment by tvillaren** [comment]
Hey @sleewoo,

Thanks for the PR, I just merged it, should be published very soon.
