### ISSUE TITLE
TS2321: Excessive stack depth comparing types 

### ISSUE THREAD

**Issue by BYohann** [fabien0102/ts-to-zod#27]
TS ERROR 

zod : 3.10
ts-to-zod : 1.2.0
Typescript 4.3.2

this TS interface  

```
export interface tag {
  tags: any[];
}
```

output 

```
export const tagSchema = z.object({
  tags: z.array(z.any())
});
```

but  produce a typescript error : 

```
TS2321: Excessive stack depth comparing types 'ZodError?>' and 'ZodError?>'.
TS2321: Excessive stack depth comparing types 'ZodFormattedError?>' and 'ZodFormattedError?>'.
TS2321: Excessive stack depth comparing types 'ZodIntersection?, U>' and 'ZodIntersection?, U>'.
TS2321: Excessive stack depth comparing types 'ZodIntersection ' and 'ZodIntersection '.
TS2321: Excessive stack depth comparing types 'ZodNonEmptyArray?>' and 'ZodNonEmptyArray?>'.
```

**Comment by fabien0102** [comment]
🤔 Strange indeed, I will need to investigate a bit. Thanks for reporting this issue

As workaround, you can use the `--skipValidation` flag, the API is well tested 😉

**Comment by fabien0102** [comment]
This seams to be related to typescript version, 4.2.3 works perfectly (I will fix the version for now I think)

Related issues:
https://github.com/microsoft/TypeScript/issues/43249
https://github.com/colinhacks/zod/issues/443

**Comment by BYohann** [comment]
I just tested it, works like a charm now, congrats and thank you
