### ISSUE TITLE
Error when referencing an imported type in an Index Signature Type

### ISSUE THREAD

**Issue by sgalcheung** [fabien0102/ts-to-zod#277]
## Feature description

To support index signature type.

### Input

```ts
// typescript type or interface causing the output
export interface ResourceLink {
    /**
     * The link url.
     * @type {string}
     * @memberof ResourceLink
     */
    href: string;
    /**
     * The link method.
     * @type {string}
     * @memberof ResourceLink
     */
    method: string;
    /**
     * Additional data about the link.
     * @type {string}
     * @memberof ResourceLink
     */
    metadata?: string | null;
}

export interface AppDto {
    /**
     * The links.
     * @type {{ [key: string]: ResourceLink; }}
     * @memberof AppDto
     */
    links: {
        [key: string]: ResourceLink;
    };
}
```

### Output

```ts
// Expected Zod schemas
export const resourceLinkSchema = z.object({
  href: z.string(),
  method: z.string(),
  metadata: z.string().optional().nullable(),
});

export const appDtoSchema = z.object({
  links: z.record(resourceLinkSchema),
});
```

**Comment by tvillaren** [comment]
Hello @sgalcheung, 
I'm puzzled, this is working correctly. The actual output is the expected one when provided the input you mention. 

Did I miss anything?

**Comment by sgalcheung** [comment]
It's an expected one.
When I ran the input, that generated nothing.

**Comment by tvillaren** [comment]
Do you have a minimum project to reproduce this? 
I run it locally on my machine, and I get exactly the expected output so you might want to look into your project configuration. 

`ts-to-zod` does support index signature type.

**Comment by sgalcheung** [comment]
I created [a minimum project](https://stackblitz.com/edit/stackblitz-starters-tvt1uq?file=generated%2FresourceLink.zod.ts) for this.

**Comment by tvillaren** [comment]
Hello, 
The project you shared doesn't match what you wrote in the ticket 😉 

When both `ResourceLink` and `AppDto` are in the same file, as you initially mentioned, it does work (see this [project](https://stackblitz.com/edit/stackblitz-starters-w4jvn5?file=Both.ts,ts-to-zod.config.js,generated%2Fboth.zod.ts))

When they're in 2 separate files, I can see the warning 
```
Warning: Some schemas can't be generated due to direct or indirect missing dependencies:
 ›   appDtoSchema
``` 
which seems to be linked to the index signature type.

**Comment by tvillaren** [comment]
```ts
import type { ResourceLink } from "./ResourceLink.ts";

export interface AppDto {
  /**
   * The links.
   * @type {{ [key: string]: ResourceLink; }}
   * @memberof AppDto
   */
  links: {
    [key: string]: ResourceLink;
  };
}
```
generates an empty file while it should generate 
```ts
// Generated by ts-to-zod
import { z } from "zod";

import { resourceLinkSchema } from "./resourceLink.zod";

export const appDtoSchema = z.object({
  links: z.record(resourceLinkSchema),
});
```

**Comment by sgalcheung** [comment]
> The project you shared doesn't match what you wrote in the ticket 😉

I'm sorry I made the trouble, both of these situations should be very common. I should mention that these are two files. or the comments are different files.
Anyway, through the minimum project, you have already known about this problem.
