### ISSUE TITLE
A validator that can access the values and require a certain field to be of a specific value

### ISSUE THREAD

**Issue by adrienlo** [fabien0102/ts-to-zod#280]
## Feature description

I'd like to be able to write a validator so I can check the values of `list` so it can be of `status: 'done'`. Is this possible?

### Input

```ts
type Foo = {
  status: 'done' | 'failed'
}

type Bar = {
  /**
   * @minimum 1 There must be at least one Foo
   * @tstype {Foo[] & { [list.length - 1]: { status: 'done' } }}
   */
  list: Foo[]
}
```

### Output

```ts
const fooSchema = z.object({
  status: z.enum(['done', 'failed'])
})

const barSchema = z.object({
  list: z
    .array(fooSchema)
    .min(1, { message: 'There must be at least one Foo' })
    .refine(list => list[list.length - 1]?.role === 'user', {
      message: 'The last foo must have the status "donea"',
    })
})

```

**Comment by tvillaren** [comment]
Hello, 

The best way to add this kind of validation is to use the `@schema` tag: 

```ts
type Foo = {
  status: "done" | "failed";
};

type Bar = {
  /**
   * @minimum 1 There must be at least one Foo
   * @schema .refine(list => list[list.length - 1]?.status === 'done', { message: 'The last foo must have the status "done"', })
   */
  list: Foo[];
};
```

This will append the `.refine(...)` bit to the generated code

**Comment by adrienlo** [comment]
Thanks for the quick reply! Did not know you could do that. Is there expanded documentation around the `@schema` tag?

**Comment by tvillaren** [comment]
Documentation is in [this section](https://github.com/fabien0102/ts-to-zod?tab=readme-ov-file#other-jsdoc-tags)
Could be a bit more extensive I guess 😄
