### ISSUE TITLE
Mark types for schema generation

### ISSUE THREAD

**Issue by MarcPorciuncula** [fabien0102/ts-to-zod#30]
## Feature description

I think it would be useful to have a way to mark only certain types for zod schema generation.

I have many cases of files that have several exported types but only some types actually need zod schemas. The current workaround for this is to split out the types that need schema generation into a separate file nearby but at the sacrifice of code colocation.

I imagine this could be done via some addition JSDoc directive on the type declaration, as those are already parsed and used for adding refinements.

**Comment by fabien0102** [comment]
I like the idea, will see what I can do 😃

**Comment by fabien0102** [comment]
@MarcPorciuncula As workaround, you can also use `nameFilter` in the config:

```diff
diff --git a/ts-to-zod.config.js b/ts-to-zod.config.js
index 00380ed..2189a13 100644
--- a/ts-to-zod.config.js
+++ b/ts-to-zod.config.js
@@ -8,6 +8,9 @@ module.exports = [
     name: "example",
     input: "example/heros.ts",
     output: "example/heros.zod.ts",
+    nameFilter: (name) => {
+      return ["Enemy"].includes(name);
+    },
   },
   { name: "config", input: "src/config.ts", output: "src/config.zod.ts" },
 ];
```

A little JSDoc tag will definitely be better, I think I will just add a `JSDocTagFilter` with the same pattern, so the user can choose their convention about the filter.

**Comment by luhmann** [comment]
I tried to achieve this by having a file that re-exports only the types I want to have validation-schemas for:

```ts
// types.ts

export type LoginInput = {
  email: string
  password: string
}
```

```ts
// input.ts
export { LoginInput } from './types'

// or even

export type { LoginInput } from './types'
```

and then use `input.ts` as input for `ts-to-zod`. This does not seem to work the types physically need to be in the file. But I could not determine why. But maybe it could serve as another idea how this feature could be supported.

**Comment by fabien0102** [comment]
Hi @luhmann
For now ts-to-zod doesn’t support multiple files, so it can’t follow the type definition. If you want to have a list of exported types, you have the previous workaround (https://github.com/fabien0102/ts-to-zod/issues/30#issuecomment-851304469)

But indeed, I like the idea of the barel pattern to select what you want to export / generate with ts-to-zod 👌
