### ISSUE TITLE
Support for `Date`

### ISSUE THREAD

**Issue by MarcPorciuncula** [fabien0102/ts-to-zod#31]
## Feature description

The `Date` type should generate `z.date()`.

It appears that currently using `Date` outputs `Warning: Some schemas can't be generated due to circular dependencies:`.

### Input

```ts
export type MyType = {
	when: Date,
};
```

### Output

```ts
export const myTypeSchema = z.object({
	when: z.date(),
});
```

**Comment by fabien0102** [comment]
Done! Thanks for the catch!
