### ISSUE TITLE
Circular dependency error for enum types

### ISSUE THREAD

**Issue by anglinb** [fabien0102/ts-to-zod#35]
## Bug description

_This could be considered a feature request rather than a bug since I haven't seen any mention of enum handling in the codebase 🤷_ 

When generating a zod validator from a type which references an enum, the generation produces a waring on the CLI and an empty generated file.

```
 ›   Warning: Some schemas can't be generated due to circular dependencies:
 ›   tagSchema
✔ Validating generated types
🎉 Zod schemas generated!
✨  Done in 1.99s.
```
### Input

```ts

export enum TagName {
	Button = 'button'
};

export type Tag = {
	name: TagName,
}

```

### Expected output

```ts
// Generated by ts-to-zod
import { z } from 'zod'
import { TagName } from '../types/tag-simple';

export const tagNameSchema = z.nativeEnum(TagName);

export const tagSchema = z.object({
  name: tagNameSchema
})

```

### Actual output

```ts

```

**Versions**

- Typescript: `v4.3.4`
- Zod: `v3.1.0`

**Comment by fabien0102** [comment]
Closed by #40
