### ISSUE TITLE
Option to generate zod objects from `IndexedAccessType`

### ISSUE THREAD

**Issue by hffmnn** [fabien0102/ts-to-zod#42]
## Feature description

We generate our types from an OpenAPI spec file. The types are nested interfaces. To generate explicit types we have to use lookup types, e.g. `type RefreshRequestBody = components["schemas"]["RequestBody"];`.

When trying to run `ts-to-zod` on these types it gives the following warning:

`Warning: 'IndexedAccessType' is not supported, fallback into 'z.any()'`

I don't know if this is possible at all, but it would be great if `ts-to-zod` could generate valid `zod` types out of lookup types.

### Input

```ts
export interface components {
    schemas: {
        RequestBody: {
            some: string;
        };
    };
}

type RefreshRequestBody = components["schemas"]["RequestBody"];
```

### Output

```ts
import { z } from "zod";

export const requestBodySchema = z.object({
    some: z.string(),
});
```

**Comment by fabien0102** [comment]
Good catch, let’s see what we can do about this 💯
