### ISSUE TITLE
Support Namespaces

### ISSUE THREAD

**Issue by FlorianWendelborn** [fabien0102/ts-to-zod#43]
## Feature description

We currently auto-generate TypeScript interfaces from openapi specs. The result of this looks something like this:

### Input

```ts
export namespace BulkDownloadParts {
	export interface PathParameters {
		service_id: number
	}

	export interface RequestBody {
		/**
		 * Define For which kind of entity you want to download parts.
		 * Will fall back to OrderLine if not set explicitly
		 *
		 */
		lineType?: 'OrderLine' | 'QuoteLine' | 'RequestForQuoteLine'
		partIds: number[]
	}

	export interface Response {
		jwt: string
		url: string
	}
}
```

#### 1. Via `namespace`

Would probably ease implementation, but is deprecated (we only use namespaces to group types, not really for actual runtime code)

```ts
// Generated by ts-to-zod
import { z } from 'zod'

export namespace BulkDownloadParts {
	export const pathParametersSchema = z.object({
		service_id: z.number(),
	})

	export const requestBodySchema = z.object({
		lineType: z
			.union([
				z.literal('OrderLine'),
				z.literal('QuoteLine'),
				z.literal('RequestForQuoteLine'),
			])
			.optional(),
		partIds: z.array(z.number()),
	})

	export const responseSchema = z.object({
		jwt: z.string(),
		url: z.string(),
	})
}
```

#### 2. Via Prefixing

```ts
// Generated by ts-to-zod
import { z } from 'zod'

export const bulkDownloadPartsPathParametersSchema = z.object({
	service_id: z.number(),
})

export const bulkDownloadPartsRequestBodySchema = z.object({
	lineType: z
		.union([
			z.literal('OrderLine'),
			z.literal('QuoteLine'),
			z.literal('RequestForQuoteLine'),
		])
		.optional(),
	partIds: z.array(z.number()),
})

export const bulkDownloadPartsResponseSchema = z.object({
	jwt: z.string(),
	url: z.string(),
})
```

#### 3. Via `object`s

```ts
export const BulkDownloadParts = {
	pathParametersSchema: z.object({
		service_id: z.number(),
	}),
	requestBodySchema: z.object({
		lineType: z
			.union([
				z.literal('OrderLine'),
				z.literal('QuoteLine'),
				z.literal('RequestForQuoteLine'),
			])
			.optional(),
		partIds: z.array(z.number()),
	}),
	responseSchema: z.object({
		jwt: z.string(),
		url: z.string(),
	})
}
```

---

Personally, I’d prefer the prefixing approach as it doesn’t use the quasi-deprecated `namespace` feature and as the object-based approach is proabably nearly impossible to tree-shake and thus would drastically increase bundle sizes for big APIs. The one in question defines 1584 interfaces with most of them being a lot more complex than this example, so it would make a noticeable difference...

**Comment by fabien0102** [comment]
Hi @FlorianWendelborn, thanks to pointing this, indeed I’m not using `namespace` at all and I totally forgot about them ^^

Indeed prefixing seams to be the simplest for this, let’s do this!

**Comment by fabien0102** [comment]
The output with my PR #44 

```tsx
// Generated by ts-to-zod
import { z } from "zod";

export const bulkDownloadPartsPathParametersSchema = z.object({
  service_id: z.number(),
});

export const bulkDownloadPartsRequestBodySchema = z.object({
  lineType: z
    .union([
      z.literal("OrderLine"),
      z.literal("QuoteLine"),
      z.literal("RequestForQuoteLine"),
    ])
    .optional(),
  partIds: z.array(z.number()),
});

export const bulkDownloadPartsResponseSchema = z.object({
  jwt: z.string(),
  url: z.string(),
});
```

**Comment by fabien0102** [comment]
Included in `v1.5.0`

**Comment by FlorianWendelborn** [comment]
Thanks @fabien0102

**Comment by Amorites** [comment]
`namespace` is not to be deprecated https://github.com/microsoft/TypeScript/issues/30994 😢

**Comment by fabien0102** [comment]
Hi @Amorites,

I didn’t get your last comment; this library is supported namespaces, don’t worry; you can see how this is processed inside the unit tests -> https://github.com/fabien0102/ts-to-zod/pull/44/files

**Comment by Amorites** [comment]
Thank you @fabien0102 

I saw there is some content in this issue like:

> #### 1. Via namespace
> Would probably ease implementation, but is deprecated (we only use namespaces to group types, not really for actual runtime code)

> Personally, I’d prefer the prefixing approach as it doesn’t use the quasi-deprecated namespace feature 

Just a reminder that `namespace` is not going to deprecate.

And I have created an issue https://github.com/fabien0102/ts-to-zod/issues/102 about the current implementation.
