### ISSUE TITLE
Required & Invalid custom strings

### ISSUE THREAD

**Issue by replete** [fabien0102/ts-to-zod#55]
## Feature description

Allow custom required and invalid strings to be configured within the JSDoc comment annotation.

* `@required` exclusively to set zod's `required_error` string (given that required is in the interface)?
* quotes around JSDoc comment value probably could be optional?
* Though not in this code example, use of VALUE,STRING JSDoc comment format probably also works for `@minLength|maxLength|pattern|format`?
* Implement would require checking the JSDoc param value for existence of a comma, and then writing the extra objects

#### Use-case
I am using this within a  express middleware to validate a request object, and want to send more useful error messages in a response when validation fails.

### Input

```ts
export interface CreateUser {
	/**
	 * @minLength 2, "Name must be at least 2 characters"
	 * @maxLength 254, "Name is too long"
	 * @required "Name is required"
	 */
	name: string
	/**
	 * @minLength 6, "Email must be at least 6 characters"
	 * @maxLength 320, "Email is too long"
	 * @format email
	 * @required "Email is required"
	 */
	email: string
	/**
	 * @minLength 6, "Password must be at least 6 characters"
	 * @maxLength 127, "Password is too long
	 * @required "Password is required"
	 */
	password: string
}
```

### Output

```ts
// Generated by ts-to-zod
import { z } from 'zod'

export const createUserSchema = z.object({
	name: z
		.string({ required_error: 'Name is required' })
		.min(2, 'Name must be at least 2 characters')
		.max(254, 'Name is too long'),
	email: z
		.string({ required_error: 'Email is required' })
		.min(6, 'Email must be at least 6 characters')
		.max(320, 'Email is too long')
		.email(),
	password: z
		.string({ required_error: 'Password is required' })
		.min(6, 'Password must be at least 6 characters')
		.max(127, 'Password is too long')
})

```

Great work on this library, contributors 👍

**Comment by fabien0102** [comment]
I love this idea! Thanks for your amazing suggestion!

**Comment by fabien0102** [comment]
@replete This feature is part of the next release (`v1.10.0`), if you want to have a try! 😃 

You have more details on the #73, any feedbacks are welcome. Thanks again for this amazing suggestion 💯

**Comment by replete** [comment]
Legendary! Look forward to testing this :) This is super cool because it's hard to rely on automated steps when they don't meet all your requirements, this looks like it's much more usable now. Awesome work!
