### ISSUE TITLE
Optional & nullable not output together on optional union type property with null value

### ISSUE THREAD

**Issue by tvillaren** [fabien0102/ts-to-zod#65]
## Bug description

When an optional property references a union type with `null`, the result is not using the `optional()` modifier

### Input

```ts
export interface A {
  a?: number | null;
}
```

### Expected output

```ts
export const aSchema = z.object({
  a: z.number().optional().nullable()
});
```

### Actual output

```ts
export const aSchema = z.object({
  a: z.number().nullable()
});
```

### Potential fix 

Did some fiddling on a fork, and found that the `isOptional` flag was not passed down in case of an union type traversal. 

**Versions**

- Typescript: `v4.5.2`
- Zod: `v1.7.0`

**Comment by tvillaren** [comment]
Actually, my PR doesn't fix all cases, only the "simple" one.

This fails: 
```ts
it("should allow nullable on optional union properties", () => {
    const source = `export interface A {
      a?: number | string | null;
    }
    `;

    expect(generate(source)).toMatchInlineSnapshot(`
      "export const aSchema = z.object({
          a: z.union([z.number(), z.string()]).optional().nullable()
      });"
    `);
  });
``` 

But I'm not sure of the expected output here...

**Comment by fabien0102** [comment]
Part of `1.8.0` release 😀
