### ISSUE TITLE
ts-to-zod support for auto generated zod object's strict()

### ISSUE THREAD

**Issue by eshita19** [fabien0102/ts-to-zod#78]
## Feature description
Couldn't find `ts-to-zod` way for enforcing [strict](https://github.com/colinhacks/zod#strict) on zod schema. 

### Input

```ts
export type Student = {
  name?:string;
};
```

### Output
export const studentSchema = z.object({
  name: z.string().optional()
});

Expected Schema
```ts
export const studentSchema = z.object({
  name: z.string().optional()
}).strict();
```

**Comment by fabien0102** [comment]
Indeed, we don't have any option for this now. You can still use `studentSchema.strict()` if you want the strict mode but I can add an option at the generation level 😃

**Comment by eshita19** [comment]
@fabien0102 It would be great if you can add it at generation level. As we don't want to modify the schema manually.
Thanks!

**Comment by fabien0102** [comment]
You don't have to modify the schema, I was thinking when you are using the schema.

```tsx
// before
studentSchema.parse({})

// after
studentSchema.strict().parse({})
```

(still in my todolist anyway ^^)

**Comment by eshita19** [comment]
@fabien0102   Tried it. But it doesn't work with nested type/interface. We would have to add `strict()` for all child types/interface.

**Comment by notflip** [comment]
@eshita19 Did you find a solution to this? I'm in a situation where I need strict on each child object

**Comment by fabien0102** [comment]
Sorry, I didn't have the time recently… But I'm always open for PR reviews 😇

**Comment by tvillaren** [comment]
Hello, 

As I have the same need (currently modifying manually my generated Zod schema after generation to add `strict` everywhere 😉), I may give it a try. 

Would it make sense to add a decorator for this?
Like the `@toExtract` one, we could have the `@useStrict` one, WDYT?

**Comment by fabien0102** [comment]
@tvillaren Be my guest! if you are on the way to try a PR, please add this in configuration (this shouldn't be the default behaviour)

About the JSDoc tag… It's a good question, I guess this could be configurable since I don't see any reasonnable default for this one (I think I will go for a `@strict` personally)

**Comment by tvillaren** [comment]
Agreed on the fact that it shouldn't be the default behaviour. 

My plan was to have it on a per-interface basis:
```
export interface A {
      /** @useStrict */
      a: {
        b: number
      }
    }
```
or 
```
/**
    * @useStrict
    */
    export type Superman = {
      name: "superman";
      weakness: Kryptonite;
      age: number;
      enemies: Array<string>;
    };
```

WDYT?

**Comment by tvillaren** [comment]
This can be closed ;)
