### ISSUE TITLE
Wrapped Type Usage Fails with Incorrect Error Messaging

### ISSUE THREAD

**Issue by ColeMurray** [fabien0102/ts-to-zod#87]
## Bug description

When using wrapped types, ts-to-zod fails with circular dependencies

### Input

```ts
export type AutoboxedType = {
  someProp: Number;
}
```

### Expected output

```ts
export const autoboxedTypeSchema = z.object({
  someProp: z.number(),
})
```

I understand the nuance here around the autoboxed type. As a user, I would expect a few changes:
1. Clear callout in the documentation that autobox types do not work / must use primitives
2. More clear error, calling out the autoboxed type usage instead of circular deps

### Actual output

```ts
 ›   Warning: Some schemas can't be generated due to circular dependencies:
 ›   AutoboxedTypeSchema
✔ Validating generated types
🎉 Zod schemas generated!
```

**Versions**

- Typescript: `v4.6.4`
- Zod: `v3.17.3`

**Comment by fabien0102** [comment]
The problem in your example is `Number` (custom type, not declared in this file) vs `number` (built-in type), but now that you are pointing this issue, I think I should be able to improve the circular dependency detection vs unknown types! 💡 

Thanks for the feedback, and sorry for the missleading error message!

**Comment by tvillaren** [comment]
The error message in that case has been: 

>  ›   Warning: Some schemas can't be generated due to direct or indirect missing dependencies:
 ›   autoboxedTypeSchema

for some time now. Closing for this purpose. 
I believe answering https://github.com/fabien0102/ts-to-zod/issues/231 could help here.
