### ISSUE TITLE
BUG: Files are not created and does not respect the folder path

### ISSUE THREAD

**Issue by Manuelbaun** [fabien0102/ts-to-zod#97]
## Bug description

As the title states, when trying to generate the zod schemas, the `*.zod.ts` file as specified, is not created.
Also it tries to access the project root instead of the path, where the file is located.

### Input

```
// cli commands
pnpm ts-to-zod ./src/source.ts ./src/source.zod.ts  OR
pnpm ts-to-zod --config models 

// ts-to-zod.config.js
module.exports = [
    {
        name: 'models',
        input: 'src/source.ts',
        output: 'src/source.zod.ts',
    },
];
```

### Expected output

```ts
// Expected Zod schemas
```

### Actual output
```
⠇ Validating generated types    Error: error TS6053: File
    '../projectroot/source.integration.ts' not found.
      The file is in the program because:
        Root file specified for compilation
    error TS6053: File '../projectroot/source.ts' not found.    
      The file is in the program because:
        Root file specified for compilation
    error TS6053: File '../projectroot/source.zod.ts' not found.
      The file is in the program because:
        Root file specified for compilation
```

Somehow it assumes the files to be located at the root of the projects, although I specify the `./src` in the file names.

However, If I move the `source.ts` to the root level, and try, I will get the same error, But if I create `source.zod.ts` and `source.integration.ts` then it generates fine.

**Versions**

- Typescript: `v4.8.4`
- Zod: `v3.19.1`
- ts-to-zod: `v1.13.1`

**Comment by cjfswd** [comment]
same behaviour here...

**Comment by tvillaren** [comment]
I've been using CLI and relative paths for a while, it seems to work fine.
